name = "Aaren's Blast Effects"
author = "Aaren"
prefix = "ASBE"
mainprefix = "z"

[binarize]
enabled = false # Default: true

[version]
major = 1 # Overrides path when set
minor = 1
patch = 0

git_hash = 0 # Default: 8